import Head from 'next/head';
import styles from '@/styles/Layout.module.css';
import Hero from '@/components/home/Hero';
import Activity from '@/components/activitySection/Activity';
import Benefit from '@/components/home/SectionBenefit';
import ForYou from '@/components/home/ForYou';
import Review from '@/components/home/SectionReview';
import { Container, Image, Row, Col } from 'react-bootstrap';

export default function Home({ activities4u, reviews }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Hero />
        <Activity />
        <Benefit />
        <ForYou activities={activities4u} />
        <Review reviews={reviews} />
      </main>
    </>
  );
}

export async function getStaticProps() {
  try {
    const { activities4u } = await import('@/data/home/activity4u.json');
    const { reviews } = await import('@/data/home/review.json');
    return { props: { activities4u, reviews } };
  } catch (err) {
    console.error(err);
  }
}
