import Head from 'next/head';
import styles from '@/styles/Layout.module.css';
import Activity from '@/components/activitySection/Activity';
import { Container, Image, Row, Col } from 'react-bootstrap';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div class="hero" style={{ backgroundColor: '#FFF6EC', height: '725px' }}>
          <Container className={styles.heroContent}>
            <h1 className={styles.captionHero}>
              Jaga Bumi
            </h1>
            <h2 className={styles.caption2Hero}>
              Lindungi Masa Depan Bersama
            </h2>
            <p className={styles.descHero}>
              Kami adalah ekosistem yang terdiri dari beragam komunitas dan relawan di berbagai tempat. Ayo gabung dan bantu kami menjalankan misi untuk menjaga bumi demi masa depan bumi yang lebih baik.
            </p>
            <button className={styles.buttonHero}>
              Ayo Mulai
            </button>
            <Image className={styles.backHero} src='/Background Hero.png' width={560} height={405} />
            <Image className={styles.fotoHero} src='/FotoHero.png' width={445} height={322} />
          </Container>
        </div>

        <Activity />

        <div class="for you" style={{ backgroundColor: '#FFF6EC', height: '1110px' }}>
          <Row className={styles.FUContent} style={{ height: '410px' }}>
            <text className={styles.textFU} style={{ color: '#242C48', height: '67px' }}>
              Manfaat Menjadi Relawan
            </text>
            <Container style={{ height: '60px', width: '1200px' }}>
              <text2 className={styles.text2FU}>
                Dapatkan berbagai manfaat ketika kamu menjadi relawan, karena disini kamu bisa menambah pengalaman serta kami senang untuk berbagi canda dan tawa.
              </text2>
            </Container>
            <Row className={styles.boxFU}>
              <Image className={styles.imageBox} src='/tujuanFU.png' />
              <text1 className={styles.textBox}>
                Memberi Tujuan
              </text1>
              <text2 className={styles.text2Box}>
                Kamu mungkin dapat menemukan tujuan dengan menjadi bagian dari sesuatu yang lebih besar dan lebih hebat dari dirimu
              </text2>
            </Row>
            <Row className={styles.boxFU}>
              <Image className={styles.imageBox} src='/relasiFU.png' />
              <text1 className={styles.textBox}>
                Bertemu teman baru
              </text1>
              <text2 className={styles.text2Box}>
                Menjadi relawan adalah salah satu cara untukmu mendapatkan relasi yang lebih luas dan teman yang sefrekuensi dengan mu
              </text2>
            </Row>
            <Row className={styles.boxFU}>
              <Image className={styles.imageBox} src='/kepekaanFU.png' />
              <text1 className={styles.textBox}>
                Meningkatkan kepekaan
              </text1>
              <text2 className={styles.text2Box}>
                Menjadi relawan di suatu komunitas meningkatkan kepekaan dan wawasan mu terhadap apa yang terjadi pada lingkungan sekitar mu
              </text2>
            </Row>
          </Row>
          <Row className={styles.FUContent} style={{ height: '500px', marginTop: '90px', padding: '0px' }}>
            <text className={styles.textFU} style={{ color: '#579E1F', height: '67px' }}>
              Aktivitas Untuk Kamu
            </text>
            <text2 className={styles.text2FU} style={{ height: '30px' }}>
              Berikut beberapa saran kegiatan yang dapat kamu lakukan
            </text2>
            <Row style={{ height: '400px', display: 'flex', alignItems: 'center', justifyContent: 'center', marginTop: '0px' }}>
              <Row className={styles.cardFU} style={{ marginLeft: '0px' }}>
                <Image className={styles.imageCard} src='/card1.png' />
                <Row className={styles.dateCard} >
                  <text className={styles.textdateC} style={{ fontStyle: 'normal', fontWeight: '700', fontSize: '16px' }}>
                    11
                  </text>
                  <text className={styles.textdateC} style={{ fontStyle: 'normal', fontWeight: '700', fontSize: '16px', color: '#7AC241' }}>
                    July
                  </text>
                  <text className={styles.textdateC} style={{ fontStyle: 'normal', fontWeight: '400', fontSize: '11px' }}>
                    2023
                  </text>
                </Row>
                <Row className={styles.dateCard} style={{ width: '205px', position: 'relative' }}>
                  <text className={styles.textdateC} style={{ fontStyle: 'normal', fontWeight: '700', fontSize: '14px' }}>
                    Membersihkan Pantai
                  </text>
                  <text className={styles.textdateC} style={{ fontStyle: 'normal', fontWeight: '700', fontSize: '14px', color: '#7AC241' }}>
                    Kuta Beach - Clean Up
                  </text>
                  <text className={styles.textdateC} style={{ fontStyle: 'normal', fontWeight: '400', fontSize: '11px' }}>
                    Pantai Kuta, Badung, Bali
                  </text>
                </Row>
                <Row className={styles.dateCard} style={{ width: '50px' }}>
                  <div className={styles.profileCard} style={{ backgroundColor: '#83EFBB' }}></div>
                  <text className={styles.textdateC} style={{ fontStyle: 'normal', fontWeight: '700', fontSize: '10px', color: '#7AC241', left: '0', textAlign: 'center', lineHeight: '12px', top: '5px' }}>
                    Pecinta Senja
                  </text>
                  <text className={styles.textdateC} style={{ fontStyle: 'normal', fontWeight: '400', fontSize: '8px', left: '0' }}>
                    komunitas
                  </text>
                </Row>
              </Row>
              <Row className={styles.cardFU}>
                <Image className={styles.imageCard} src='/card2.png' />
                <Row className={styles.dateCard}>
                  <text className={styles.textdateC} style={{ fontStyle: 'normal', fontWeight: '700', fontSize: '16px' }}>
                    24
                  </text>
                  <text className={styles.textdateC} style={{ fontStyle: 'normal', fontWeight: '700', fontSize: '16px', color: '#7AC241' }}>
                    July
                  </text>
                  <text className={styles.textdateC} style={{ fontStyle: 'normal', fontWeight: '400', fontSize: '11px' }}>
                    2023
                  </text>
                </Row>
                <Row className={styles.dateCard} style={{ width: '205px', position: 'relative' }}>
                  <text className={styles.textdateC} style={{ fontStyle: 'normal', fontWeight: '700', fontSize: '14px' }}>
                    Membersihkan Pantai
                  </text>
                  <text className={styles.textdateC} style={{ fontStyle: 'normal', fontWeight: '700', fontSize: '14px', color: '#7AC241' }}>
                    Bersih - Bersih Nunggalan
                  </text>
                  <text className={styles.textdateC} style={{ fontStyle: 'normal', fontWeight: '400', fontSize: '11px' }}>
                    Pantai Nunggalan, Badung, Bali
                  </text>
                </Row>
                <Row className={styles.dateCard} style={{ width: '50px' }}>
                  <div className={styles.profileCard} style={{ backgroundColor: '#83D5EF' }}></div>
                  <text className={styles.textdateC} style={{ fontStyle: 'normal', fontWeight: '700', fontSize: '10px', color: '#7AC241', left: '0', textAlign: 'center', lineHeight: '12px', top: '5px' }}>
                    Tepi Pantai
                  </text>
                  <text className={styles.textdateC} style={{ fontStyle: 'normal', fontWeight: '400', fontSize: '8px', left: '0' }}>
                    komunitas
                  </text>
                </Row>
              </Row>
              <Row className={styles.cardFU}>
                <Image className={styles.imageCard} src='/card3.png' />
                <Row className={styles.dateCard}>
                  <text className={styles.textdateC} style={{ fontStyle: 'normal', fontWeight: '700', fontSize: '16px' }}>
                    02
                  </text>
                  <text className={styles.textdateC} style={{ fontStyle: 'normal', fontWeight: '700', fontSize: '16px', color: '#7AC241' }}>
                    Aug
                  </text>
                  <text className={styles.textdateC} style={{ fontStyle: 'normal', fontWeight: '400', fontSize: '11px' }}>
                    2023
                  </text>
                </Row>
                <Row className={styles.dateCard} style={{ width: '205px', position: 'relative' }}>
                  <text className={styles.textdateC} style={{ fontStyle: 'normal', fontWeight: '700', fontSize: '14px' }}>
                    Membersihkan Pantai
                  </text>
                  <text className={styles.textdateC} style={{ fontStyle: 'normal', fontWeight: '700', fontSize: '14px', color: '#7AC241' }}>
                    Membersihkan Balangan
                  </text>
                  <text className={styles.textdateC} style={{ fontStyle: 'normal', fontWeight: '400', fontSize: '11px' }}>
                    Pantai Balangan, Badung, Bali
                  </text>
                </Row>
                <Row className={styles.dateCard} style={{ width: '50px' }}>
                  <div className={styles.profileCard} style={{ backgroundColor: '#E77F92' }}></div>
                  <text className={styles.textdateC} style={{ fontStyle: 'normal', fontWeight: '700', fontSize: '10px', color: '#7AC241', left: '0', textAlign: 'center', lineHeight: '12px', top: '5px' }}>
                    Peduli Pesisir
                  </text>
                  <text className={styles.textdateC} style={{ fontStyle: 'normal', fontWeight: '400', fontSize: '8px', left: '0', color: '#242C48' }}>
                    komunitas
                  </text>
                </Row>
              </Row>
              <button className={styles.buttonFU}>
                Aktivitas Lainnya
                <Image src='/up.png' style={{ width: '24px', height: '24px', marginLeft: '8px', marginBottom: '2px' }} />
              </button>
            </Row>
          </Row>
        </div>

        <div class="review" style={{ backgroundColor: '#FAEADE', height: '625px' , width: '100%'}}>
          <Row className={styles.reviewBack} >
            <text className={styles.textFU} style={{ alignItems: 'normal', height: '58px', color: '#242C48' }}>
              Ulasan Relawan
            </text>
            <div className={styles.elemenReview}></div>
            <text2 className={styles.text2FU} style={{ height: '24px', alignItems: 'normal' }}>
              Kata - kata relawan tentang kami
            </text2>
            <Row className={styles.backCard}>
              <Col className={styles.cardReview}>
                <Container style={{ background: '#EB7C6D' }} className={styles.profileReview}></Container>
                <Container style={{ width: '325px', height: '250px', background: '#FFF6EC', borderRadius: '12px' }}>
                  <text style={{ fontWeight: '700' }} className={styles.textReview}>
                    Madya Sentosa
                  </text>
                  <text className={styles.textReview}>
                    Mahasiswa
                  </text>
                  <Image className={styles.imageReview} src='/gapReviewCard.png' width={'57px'} height={'57px'} />
                  <text className={styles.text2Review} >
                    Senang rasanya bisa bergabung menjadi salah satu relawan di kegiatan-kegiatan seperti ini, rasanya seperti kita menjadi bagian penting dari perjalanan menuju bumi yan lebih baik.
                  </text>
                </Container>
              </Col>
              <Col className={styles.cardReview}>
                <Container style={{ background: '#33B7E1' }} className={styles.profileReview}></Container>
                <Container style={{ width: '325px', height: '250px', background: '#FFF6EC', borderRadius: '12px' }}>
                  <text style={{ fontWeight: '700' }} className={styles.textReview}>
                    Steven Belva
                  </text>
                  <text className={styles.textReview}>
                    Mahasiswa
                  </text>
                  <Image className={styles.imageReview} src='/gapReviewCard.png' width={'57px'} height={'57px'} />
                  <text className={styles.text2Review} >
                    Pengalaman pertama ku menjadi relawan di Peduli Bumi engga akan pernah terlupa. Kegiatannya seru dan asyik banget, dan aku bisa bertemu dengan teman-teman baru dari berbagai tempat
                  </text>
                </Container>
              </Col>
              <Col className={styles.cardReview}>
                <Container style={{ background: '#73E285' }} className={styles.profileReview}></Container>
                <Container style={{ width: '325px', height: '250px', background: '#FFF6EC', borderRadius: '12px' }}>
                  <text style={{ fontWeight: '700' }} className={styles.textReview}>
                    Gus Ryan
                  </text>
                  <text className={styles.textReview}>
                    Mahasiswa
                  </text>
                  <Image className={styles.imageReview} src='/gapReviewCard.png' width={'57px'} height={'57px'} />
                  <text className={styles.text2Review} >
                    Sumpah kalian harus banget coba jadi relawan di Peduli Bumi. Awalnya aku juga skeptis banget sama kegiatan-kegiatan kayak gini, tapi setelah diajakin temen dan dijalanin ternyata kegiatannya seru banget
                  </text>
                </Container>
              </Col>
            </Row>
          </Row>
        </div>

      </main>
    </>
  );
}
