import Head from 'next/head';
import styles from '@/styles/Layout.module.css';
import Hero from '@/components/home/Hero';
import Activity from '@/components/activitySection/ActivityType';
import Benefit from '@/components/home/SectionBenefit';
import Recommendation from '@/components/home/RecommendSection';
import Review from '@/components/home/SectionReview';
import { Container, Image, Row, Col } from 'react-bootstrap';

export default function Home({ recommendation, reviews }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Hero />
        <Activity />
        <Benefit />
        <Recommendation activities={recommendation} />
        <Review reviews={reviews} />
      </main>
    </>
  );
}

export async function getStaticProps() {
  try {
    const { recommendation } = await import('@/data/home/recommendation.json');
    const { reviews } = await import('@/data/home/review.json');
    return { props: { recommendation, reviews } };
  } catch (err) {
    console.error(err);
  }
}
